version: "3.7"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      #- "5672:5672"
      - "15673:15672"
    networks:
      - dexi-gateway
    restart: unless-stopped
  dexicash:
    image: "dexi/dexicash:latest"
    links:
      - "rabbitmq:dexi-rabbitmq"
    depends_on:
      - rabbitmq
    networks:
      - dexi-gateway
    restart: unless-stopped
networks:
  dexi-gateway:
    driver: overlay
    attachable: true
